### ISSUE TITLE
add addon for CF7

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#101]
https://wpinvoicing.com/support/topic/integration-of-quotes-addon-with-contact-form-7-cf7/

**Comment by wpdev10** [comment]
Please find the following description regarding the functionality of this add-on:

- Create cf7 from using predefined required fields to create a quote from the form.
- When a user submits their requirements from the cf7 form then it will automatically create a new quote in admin side with the fields filled from the cf7 form.
- We will not send any notification from our plugin after submitting the form as it will depend on the settings of the cf7 form.
- If the email address that the client fills in is not already linked to a client, the plugin will automatically create a new client with this email.
- After creating quote admin can fill the items and its price from backend and send the quote to the client to approve/decline.
- Once the client accepts it then it will convert/generate an invoice which will send the link to the client for paying the invoice.

Let me know your inputs here!

**Comment by wpdev10** [comment]
Addon is ready for testing: github.com/AyeCode/wpi-cf7
