### ISSUE TITLE
Use custom post type for cart_details

### ISSUE THREAD

**Issue by Mte90** [AyeCode/invoicing#130]
I am using this plugin for an event payment system so I already have a post type for users but I don't want to duplicate them for the cart. actually seems the only solution because if I use an id of a different post type the user info and cart details like cost are not saved.

**Comment by pol76** [comment]
Hi Daniele,

we are glad to hear that you are using WPI! 

Stiofan or Kiran we'll get back to you asap. Probably after the week end though.

Thanks for your patience!

**Comment by Stiofan** [comment]
Hello @Mte90 ,

I am not sure what you mean, we use the standard WP Users table which is not a CPT, can you explain the problem you are having more?

Thanks,

Stiofan

**Comment by Mte90** [comment]
Yes of course, I need that in the cart details the id is from a custom post type and not of the `cart` post type of this plugin. 
I need that the invoice is filled with this post type that are about athletes data tab (so no users of wordpress) so I want to avoid duplication inside the `cart` post type and use that as cart stuff.
The id is not from the cart post type the rest of information like user_info are not saved and also the cart_details itself.

**Comment by Stiofan** [comment]
I am still not sure what you mean, are you trying to use a CPT instead of a user?  Maybe an example will help, can you provide a example?

**Comment by Mte90** [comment]
```
'cart_details' => array(
				array(
				'id' => [an ID],
				'quantity' => 1,
				'custom_price' => $cost
			)
),
```

Here as ID I want to use an id of a different post type and not of the cart of the plugin itself.

**Comment by Mte90** [comment]
Ok I have done a pr that add the support to use on cart_details a custom post type :-)

**Comment by kprajapatii** [comment]
Hello @Mte90,

Thanks for your contribution. :)

The ID in cart details used to link the item & invoice. Some times we need to use additional items data like currently we have about recurring feature. The recurring data are stored in item meta and not in the cart details. ID in the cart is used to make bridge between item & invoice.

In your case we have other options available to link post type to the cart item.
You can link up the cart item to external ID via cart item meta. See https://wpinvoicing.com/docs/wpinv_insert_invoice/#example-2
Ex:
```
'cart_details'      => array(
        array(
            'id'            => 2118,
            'quantity'      => 1,
            'custom_price'  => '100.00',
            'meta'          => array(
                'post_id'   => 1239
            )
        ),
    ),
```

Or you can also link up the invoice item to external post type. See https://wpinvoicing.com/docs/wpinv_create_item/#example-2
Ex: 
```
$data = array(
    'type'                 => 'custom',
    'title'                => __( 'Advance Item', 'textdomain' ),
    'custom_id'            => 123456,
    'price'                => '99.00',
    .......
 );
```
Here you can use your post_type as a type and post_ID as custom_id.

Thanks,
Kiran

**Comment by Mte90** [comment]
My issue that I can have like 100 different post types that I need to add in the invoice itself (as cart item) so I cannot create an item for everyone on the cart with duplicates. With my patch I use my post type for cart items pretty easily and without issue.
`'id'            => 2118,` I imagine that this is a cart item of the post type wpi_item and I want that in the invoice there are the titles of my post type and not of the invoicing post type.

Also the second example seems that is to create an item, my issue is that I don't want to create an item because I have another post type for that with a different purpose.

**Comment by kprajapatii** [comment]
Hello,

We have some features link discount section, tax section that needs item ID  from the wpi_item. Your code will not work for non post type items.

In your case you can follow what we have in our Payment Manager plugin. You can create one item per each post_type and use that item ID in cart for all invoices within that post_type. The post ID can be stored in item meta.

In second example you can use your own type instead of "custom". Ex :
```
$data = array(
    'type'                 => 'my_package',
    'title'                => __( 'Advance Item', 'textdomain' ),
    'custom_id'            => 123456,
    'price'                => '99.00',
    .......
 );
```
OR
```
$data = array(
    'type'                 => 'my_post_type',
    'title'                => __( 'Advance Item', 'textdomain' ),
    'custom_id'            => 123456,
    'price'                => '99.00',
    .......
 );
```

Let us know.

Thanks,
Kiran

**Comment by Mte90** [comment]
Uhm actually I don't use tax or discount, I apply the discount by code and for tax I already opened a ticket https://github.com/AyeCode/invoicing/issues/134

Based on my needs I need to do everything using code and not settings of the plugin itself. I am using this plugin as a way to simplify the invoice generation, payments etc but for tax/fee and discounts I do on my own based on the order that I am doing and from different factors so is not possible for me o use the settings that are not so flexible.
