### ISSUE TITLE
PDF invoices

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#133]
We need a button to allow users to download a PDF invoice.
1. should have option to enable/disable from settings
2. should add button to allow user to download pdf invoice
3. template should match standard layout but be able to be replaced in child theme or filter.

**Comment by Stiofan** [comment]
@pol76 do we add this in core or addon?

**Comment by kprajapatii** [comment]
As my point of view, i think separate addon will be good here.
- It keeps plugin size lower because of PDF library
- We can send pdf attachment in email to users.

**Comment by pol76** [comment]
I agree it should be an Add-on and we should make it a paid extension.

**Comment by Stiofan** [comment]
https://github.com/AyeCode/wpinv-pdf

**Comment by kprajapatii** [comment]
Plugin ready for testing

https://github.com/AyeCode/wpinv-pdf/pull/2
