### ISSUE TITLE
Add fee by code on the order

### ISSUE THREAD

**Issue by Mte90** [AyeCode/invoicing#134]
As example I need to add on every order 2 different voice:

* 0.30 euro + 3.5% of the total
* 1 euro

Seems actually that is done automatically by the plugin settings and not by code but my requirements need this fees in every order.

**Comment by Mte90** [comment]
Looking on the code seems that the taxes are based for every cart item, there is no way for a tax for all the invoice itself like as I need.

**Comment by Mte90** [comment]
I am trying to adding this fixed fee on the order with:

```
		add_action( 'wpinv_insert_invoice',  'aggiungi_commissioni' , 9999, 2 );
function aggiungi_commissioni( $invoice_id, $invoice_data ) {
		$invoice = new WPInv_Invoice( $invoice_id );
		$invoice->add_fee( array(
			'label' => __( 'Service', CR_TEXTDOMAIN ),
			'amount' => 1,
			'type' => 'fee',
			'id' => '',
			'no_tax' => false,
			'item_id' => 0,
				), true );
		$invoice->save();
	}
```

But seems that that fee is not saved, looking on https://github.com/AyeCode/invoicing/blob/master/includes/class-wpinv-invoice.php#L897 seems that a label defined is not so good so I already commented that line but seems not enough to save the new fee.
I will keep to investigate.

**Comment by Mte90** [comment]
Looking on the class the fees are in the object but not saved and also the method `add_fee` is not used in the code of the plugin so I don't know how to investigate.

**Comment by Stiofan** [comment]
What is the best way to contact you?  If we can chat over skype or slack i'll be able to help more, you can contact me on info [@] wpinvoicing.com
