### ISSUE TITLE
Mollie.com integration

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#141]
Hi,

We also need something like this: https://wordpress.org/plugins/mollie-payments-for-woocommerce/

https://www.mollie.com/en/

Thank you,

**Comment by wpdev10** [comment]
https://github.com/AyeCode/wpinv-mollie/

**Comment by wpdev10** [comment]
https://github.com/AyeCode/wpinv-mollie/

**Comment by wpdev10** [comment]
Released!
