### ISSUE TITLE
Squareup payment gateway

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#142]
please put this into the queue of payment gateways to develop:

https://squareup.com/help/us/en/article/3853-square-s-e-commerce-api-faqs

Please see: https://wpinvoicing.com/support/topic/adding-squareup/#post-822

Thanks

**Comment by wpdev10** [comment]
PR created at https://github.com/AyeCode/wpinv-square-payment

**Comment by wpdev10** [comment]
PR merged. So closing this issue.
