### ISSUE TITLE
Not genereate order until payment is done

### ISSUE THREAD

**Issue by Mte90** [AyeCode/invoicing#144]
Actually we have the problem that we are generating the order with a sequential number and that number keep growing also if the previous ones are not paid.
For the italian fisco this is a incorrect behaviour because the number is growing without the previous invoice are paid.
Usually instead there is the order that when is paid generate the invoice.
Now I am wondering how to do it that without create a post type, maybe until the order is not paid the invoice as a different number and only when is paid has the latest invoice number.

**Comment by pol76** [comment]
Hi,

Invoice = a list of goods sent or services provided, with a statement of the sum due for these; a bill.

An Invoice is a request for payment, not a receipt of payment. An Invoice can be paid or unpaid.

The Italian fiscal system allows for unpaid invoices too. (receivables - sospesi.)

Thanks,

Paolo

p.s. I'm Italian too

**Comment by Mte90** [comment]
Yeah I know but we cannot accept to have invoices not paid in the system with a sequential number this is the mainly problem.

**Comment by pol76** [comment]
why not?

**Comment by Mte90** [comment]
Because this create issues with the economic system and require more manual work to check the status of everything. Also this require to register all the order that was an error or incomplete that people do again on the fiscal system.
WooCommerce as example in all the invoice plugisn their number can be different from the order itself.

**Comment by pol76** [comment]
Ok, I just discussed this with Stiofan and we'll investigate it further. I'm opening another issue.

**Comment by Mte90** [comment]
Thank you! For me will be enough a filter/option to use a different number for the unpaid invoice in that way will be simple to resolve the issue.

**Comment by pol76** [comment]
https://github.com/AyeCode/invoicing/issues/145

**Comment by Stiofan** [comment]
> Thank you! For me will be enough a filter/option to use a different number for the unpaid invoice in that way will be simple to resolve the issue.

The post title and slug are related to this so i am not sure how you would filter this?
