### ISSUE TITLE
Add option to assign invoice ID after payment received

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#145]
This would prevent dealing with unpaid invoices.

**Comment by Mte90** [comment]
There is a deadline for that? I need on a current project :-)

**Comment by Mte90** [comment]
Do you have any suggestions about where I need to patch it? I need that for the next week so in case I can implement it and do a pr.

**Comment by Mte90** [comment]
Looking at the code the best place for that is when there is the change of status and execute `wpinv_update_invoice_number` that do that check.

**Comment by Mte90** [comment]
Ok I have done a pr but I am not sure if cover all the cases, but when a new invoice is done use the id and on payment (or change of status from backend) is used an invoice number.
Someone can say if fit all the cases? I don't know so much the code of this plugin :-)

**Comment by pol76** [comment]
HI Daniele,

tomorrow is black friday, which is the busiest time of the year for us. Unfortunately we won't have time to look into this before next week.

Thanks for your patience!

**Comment by Mte90** [comment]
No worry in the meantime work for us :-)

**Comment by Stiofan** [comment]
@Mte90 are you still using this?

**Comment by Mte90** [comment]
No we are not using anymore invoicing

**Comment by picocodes** [comment]
This is currently not feasible. The payment forms can serve as kind of a workaround.
