### ISSUE TITLE
Notification should be sent in user's default language

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/invoicing#146]
https://wpinvoicing.com/support/topic/not-correct-language-on-back-end/#post-876

**Comment by kprajapatii** [comment]
Fixed
https://github.com/AyeCode/invoicing/pull/126/commits/59bff9f3026971d081c9d077c0575e7386054b6b

**Comment by wpdev10** [comment]
Fixed and PR merged. So closing this issue.
