### ISSUE TITLE
WPI V1.1.0 bugs

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#150]
1. ~~In subscription view, clicking customer name brings you to broken screen.~~
2. In subscription view the subscription ID is not clickable (should take you to gateway site to view sub info)
3. Auto reminders get listed in notes as "Manual reminder sent to the user." should say "Automated reminder sent to the user."
4. Subscription dates on invoice and subscription are wrong, they are the date the invoice was created and not the date it was paid.
This is all i have found so far on the upgrade site i will test more on the test site.

**Comment by kprajapatii** [comment]
1) is fixed

**Comment by kprajapatii** [comment]
2. 3. & 4) Fixed
https://github.com/kprajapatii/invoicing/commit/39902a62ccc672149bf99e0261f2bed5f127b550
