### ISSUE TITLE
1.1.0 - User cancel subscription error

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#151]
If a user tries to cancel a subscription through the [wpinv_subscriptions] shortcode a php error is shown
`Fatal error: Call to undefined method WPInv_Subscription::is_recurring() in /home/ppldb/public_html/wp-content/plugins/geodir_payment_manager/includes/geodir-invoicing-functions.php on line 919`

**Comment by kprajapatii** [comment]
Not a bug. 
It happened due to files are not updated.
