### ISSUE TITLE
Company name field, force show

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#161]
we let all fields be set to show or not but the company name only shows at checkout depending on tax rules, we should have an option to force show it no matter what.

**Comment by wpdev10** [comment]
Can you explain more details here? 

What I understand is we should add the same option in fields setting tab with input type checkbox called "Force show company name at checkout". If checked it will display company name no matter what tax rule is.

Please correct me where I am wrong.

**Comment by Stiofan** [comment]
This is correct
