### ISSUE TITLE
great feedback to improve our offering

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#163]
https://curtismchale.ca/2018/02/05/freelance-invoicing-pipedream/#comment-497166

**Comment by curtismchale** [comment]
so you're building it for me?

**Comment by pol76** [comment]
As I said in my comment, we aim to make our plugin the best out there. We'll definitely use your post as feedback to improve our plugin, but don't take this as a promise to build it in details as you want it and within a time frame. It could take years before we get to that level of details.
Thanks
