### ISSUE TITLE
ER: Enable manual recurring invoicing for pre-bank transfer

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/invoicing#175]
Buyer has requested that pre-bank transfer allow recurring.

Would it possible to enable recurring invoicing without the expiry process?

The site manager would need to manually adjust listing status, but at least invoices would be generated for recurring items.

At this time it is not possible for recurring items to trigger the pre-bank transfer gateway as  a payment method at all.

Requested here:
https://wpgeodirectory.com/support/topic/reoccurring-payments/#post-443675

Note: This would require some way to mark the subscription start date, a manual intervention on the part of the site manager.

Perhaps a new addon like "Advanced Bank Transfer for Recurring Manual Payments" or something.

woo subscriptions has this
https://docs.woocommerce.com/document/subscriptions/renewal-process/#section-4

**Comment by wpdev10** [comment]
Need inputs from @Stiofan regarding how it should work.

**Comment by alexrollin** [comment]
https://wpinvoicing.com/support/topic/subscriptions-dont-start-if-invoice-is-marked-as-paid-by-admin/#post-4275
https://wpinvoicing.com/support/topic/subscriptions-and-pre-bank-transfer/#post-4282

**Comment by picocodes** [comment]
This is possible via the manual subscriptions addon
