### ISSUE TITLE
Subscription Management options

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/invoicing#182]
All gateways that support recurring billing have 0 or more options for remote management of custom subscriptions.

If the gateways supports a feature, then it should be available with the subscription management options for end users;

Options might include:
 - Cancel or Suspend an active subscription
 - Reactivate a suspended subscription
 - Resubscribe an expired or canceled subscription
 - Pay for a renewal order when the automatic recurring payment failed or the subscription uses manual renewals
 - Change the Payment Method used for automatic recurring payments

related topics
https://wpinvoicing.com/support/topic/recurring-payment-cancellation-button/#post-2254

need for documentation of end user options:
https://wpgeodirectory.com/support/topic/how-to-cancel-reoccurring-payments/#post-452598

**Comment by wpdev10** [comment]
We already have the functionality to cancel the subscription on our subscription history page. Changing the payment method is not feasible I think as when the first payment is created the profile ID is assigned to the subscription which is different for all the gateways. This may require major customization. Needs inputs from @Stiofan
