### ISSUE TITLE
Candidate for next Payment Gateway - Square

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#196]
https://squareup.com/us/en

Thanks

**Comment by wpdev10** [comment]
Hi @pol76 ,

We have already started with this payment gateway. See https://github.com/AyeCode/invoicing/issues/142

Let me know if I am missing anything.

**Comment by pol76** [comment]
Thanks, Patrik... 
I didn't know we already had it in our list.

**Comment by pol76** [comment]
I should say I didn't remember... :-)
