### ISSUE TITLE
ER / Addon - Gateway fees

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/invoicing#202]
Enable site admin to add fees to the charges to cover gateway fees.

**Comment by alexrollin** [comment]
Request https://wpgeodirectory.com/support/topic/payment-gateways-and-paypal-fees/#post-487183

**Comment by picocodes** [comment]
There is not a simple way for us to calculate gateway fees beforehand. A workaround for the user is to include the gateway fees in their prices.
