### ISSUE TITLE
Subscription emails

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#206]
https://wpinvoicing.com/support/topic/feature-request-send-payment-notifications-only-on-first-payment-no-renewals/

Are sub emails sending reminders or do they mean just a thanks for paying email?
If just a thanks for ur payment maybe we should add that as an option?

**Comment by wpdev10** [comment]
Sub emails are not a reminders, they are reciept for the renewal payment. Will add an option to turn on it and make it off by default.
