### ISSUE TITLE
ER - Improve backend UX - allow removal of all items

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/invoicing#223]
it is very confusing not to be able to delete an item when there is only one item.

further, when the item is recurring, it is not possible to add another item at all, so, the entire invoice must be restarted if the wrong item was added.

https://wpinvoicing.com/support/topic/no-x-to-remove-items/#post-3609

**Comment by picocodes** [comment]
https://github.com/AyeCode/invoicing/pull/262
