### ISSUE TITLE
If pay by bank account selected invoice should show indicator

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#226]
If a user seelcts pay via bank etc, then in the backend the admin should see a sign they should look out for this in their bank account.

**Comment by wpdev10** [comment]
Any reference or idea what should we display? 

I can think of the following things:
1. Once paid, add a note like "Invoice is pending. Please confirm with the bank and update the status to paid."
2. Admin notice on that invoice with some message like above

@Stiofan Need your suggestions as well.

**Comment by Stiofan** [comment]
just something like in status column after Pending (bank transfer)
