### ISSUE TITLE
Extension page bugs and improvements

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#232]
Yesterday I tried installing a payment gateway for invoicing via the extension page.

1st I realized it can only be done for memberships, not for individual purchases.

Then after adding a membership license key, I was still not able to install anything. I only had the Get It button instead of the install button.

We need to make sure this works flawlessly for both membership licenses and individual licenses.

Thanks

**Comment by pol76** [comment]
Actually after further testing I noticed the add-ons page appears to be working, but not the payment gateway page.

**Comment by Stiofan** [comment]
Fixed will be in next release
