### ISSUE TITLE
Price manager for WP Job Manager

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#235]
https://wpinvoicing.com/support/topic/wp-job-manager-integration/#post-3826

This would probably sell a lot cause it would allow people to work without WooCommerce that is overkill.

Please let me know if it is something we could have ready before March 2020.

Thanks,

Paolo

**Comment by picocodes** [comment]
I've had a spin at WP Job Manager and a WPI Addon seems like something we can implement in a week max.

If I understand the question, we are just porting https://wpjobmanager.com/add-ons/wc-paid-listings/ to Invoicing. Right?

**Comment by pol76** [comment]
That's correct Brian, so a beta before the end of the year is absolutely possible?
 
Thanks

**Comment by picocodes** [comment]
Yeah
