### ISSUE TITLE
Changes for Partner Verification

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#238]
>  I did have some feedback on a few requirements that need to be met (https://stripe.com/docs/partners/requirements#specific): 
> 
> - Specify a Stripe API version for all requests:
> Your integration does not appear to specify a Stripe API version on every request. When we make backwards-incompatible changes to the API, we release new, dated versions. All requests will use your account API settings, unless you override the API version. To set the API version on a specific request, send a Stripe-Version header, which is exposed via a helper method in many of our API client libraries. You can read more about how Stripe’s API versioning works at https://stripe.com/docs/api#versioning.
> 
> - Use setAppInfo to identify your Partner integration:
> Your integration doesn’t appear to identify itself via the SetAppInfo API. Because your plugin runs on your user’s infrastructure, we need a way to attribute all API traffic from each installation of your plugin to your Stripe Partner account. You can identify your plugin’s traffic by setting the value of your `partner_id` from your Stripe Dashboard (https://dashboard.stripe.com/partners/settings) as the value of the `partner_id` attribute in the SetAppInfo hash. You can read about how to use the SetAppInfo API, as well as see example code for each of our API client libraries in our docs at https://stripe.com/docs/building-plugins#setappinfo.

So we need to make sure we do both those things.

Our partner id is: pp_partner_FounODljaTLlZL

**Comment by picocodes** [comment]
https://github.com/AyeCode/wpinv-stripe-payment/pull/34
