### ISSUE TITLE
Pre-payment reminders

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#248]
We currently have a "Payment Reminder" email system that will chase users up but we don't have a built in pre-reminder email. Lets add that.

GD Payments manager adds a listing expiry email reminder, you might want to look at that for tips.  If GD is active the WPI reminder should not send for GD items.

If you have any questions please let me know.

Stiofan

**Comment by picocodes** [comment]
A system to remind users to renew their subscriptions?

**Comment by Stiofan** [comment]
No, just a friendly message like;

> Hello John Doe,
> 
> Your subscription for invoice ##123 will renew on January 30, 2020.
> 
> This is just a friendly reminder :)
