### ISSUE TITLE
ER All skipping generation of invoice for free items

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/invoicing#252]
https://wpgeodirectory.com/support/topic/prevent-issuing-invoices-for-free-packages/#post-527539

**Comment by alexrollin** [comment]
I cannot imagine this is a good idea for most folks in the EU, where invoices are sort of the law of the land, and invoice numbers matter more than so many other things.

Maybe there is a technical way to do this that can skirt around that

**Comment by alexrollin** [comment]
https://wpgeodirectory.com/support/topic/free-package-shows-invoices-tab-on-the-user-profile/#post-527596

**Comment by alexrollin** [comment]
another request

https://wpinvoicing.com/support/topic/skip-invoice-for-free-items-urgent-needed/#post-4051

**Comment by alexrollin** [comment]
https://wpgeodirectory.com/support/topic/prevent-0-invoices-from-generating/

**Comment by alexrollin** [comment]
https://wpinvoicing.com/support/topic/how-to-avoid-invoicing-for-free-entries/#post-4509

**Comment by picocodes** [comment]
I think @kprajapatii has fixed this in the pricing manager addon. Closing it now.
