### ISSUE TITLE
Remove items from invoice

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#261]
HI guys, once an item has been added to an invoice there is no way to remove it. The only way appear to be deleting the invoice and start over. Any reason for this?

Thanks,

**Comment by pol76** [comment]
Please also consider the option to remove the quantity for an item. If for example, I click twice by mistake, I should be able to go back to 1 without having to start over.

**Comment by picocodes** [comment]
https://github.com/AyeCode/invoicing/issues/261

![invoice items](https://user-images.githubusercontent.com/19934448/74713762-4ce6db00-523a-11ea-8c84-aafb84128e8d.jpg)

Clicking on the X icon reduces the quantity.
