### ISSUE TITLE
steps to rebranding WPI

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#265]
**1 Change logo and name to GetPaid.** 
Stiofan to buy wpgetpaid.com and setup site
Basanta to design a new logo

_**2 Merge Stripe plugin into core PayWP.**_ Paused

**3 Make it easy to modify the checkout form** 
add/remove required fields up to accepting payments only with email and credit card or more complex forms like these: https://wppayform.wpmanageninja.com/event-registration-form/.
Assigned to Brain 

**4 Integrate with a pricing table.**
Select the best free lightweight pricing table and integrate it to add our buy now button in the table.
Assigned to Brain 

**5 Put the focus more on payments less on invoicing on both website and wp.org page.** 
Assigned to Paolo for content and Basanta for graphics

**6 Write a blog post describing how we integrated PayWP with WPJM.** 
A tutorial with tech details for developers
Paolo and Brian to work on this.

**7 Introduce AdsWP as a free add-on for PayWP.**
Stiofan and Paolo to push this out.

**8 Outreach sites linking to WPI to let them know about rebranding.**
Assigned to Paolo

**Comment by picocodes** [comment]
Number 3 is the easiest to implement and I'll start with that.

**Comment by pol76** [comment]
I tested https://ppldb.com/wpi a bit today. This is a list of things that we can improve.

1 need easy way to get the code for the "Buy Now" button (shortcode in a metabox for each item?) This should be compatible with Elementor Dynamic content.
2 reorder wp menu (1 items 2 forms 3 invoices 4 discounts 5 reports 6 subscriptions 7 settings 8 extensions)
3 add new item on create form page is missing the 2 select fields for taxes and item type. 
4 make sure check-out experience with buy now button is equal to forms (open a custom form in a lightbox like gumroad?)
5 it needs basic "revenues and other insights" dashboard (similar to EasyDigitalDownloads) add-on?.
6 forms should be compatible with Elementor dynamic content too.

**Comment by pol76** [comment]
7 We need an option for quantity in forms

**Comment by Stiofan** [comment]
@picocodes i can help with any Elementor stuff

**Comment by Stiofan** [comment]
### New shortcode/widget/block [getpaid]

This will be used to:
1. Display payment forms [getpaid form=123]
2. Display button to open payment form in lightbox. [getpaid form=123 button="Buy Me"] (this will output a button "Buy Me" and when clicked will load the form via ajax in a lightbox)
3. Display the same same as above but for an individual item [getpaid item=321] or [getpaid item=321 button="Buy Watch"]

We would show this shortcodes on the items list view and on the edit page.

### Default checkout
To make everything consistent our old checkout needs to be brought inline with our new system, my idea would be to have a form called "Checkout (default)" which is added on install and can't be deleted.  A user can customize it just like the other forms but they can't add items to it.  This is the form that would be used when buying an individual item in point 3.
