### ISSUE TITLE
Add Pay Form CPT

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#283]
Lets add a new CPT that users can use to add a payment form.

We will then add super duper widgets such as 

- form open (this will have form settings)
- custom fields (user can set any type of field, text, textarea, select, etc)
- payment select
- items select
- ..... etc
- form close.

Start the CPT setup, i can help with widgets if needed.

**Comment by Stiofan** [comment]
@picocodes the new user creation when logged out fails

**Comment by pol76** [comment]
Forms need validation. If no item selected, the invoice is generated for all Items. There should be an alert asking to select at least 1 item when clicking the Pay Now button.

**Comment by pol76** [comment]
Please add an option to add Items with "pay what you want" instead of price.
