### ISSUE TITLE
Payment Form Flow

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#289]
Ideas:

1. Enter details, click buy
2. Creates invoice in the background with a special status (we will come back to this later)
3. Do payment via ajax or send to gateway (stay on page if possible)
4. Mark invoice paid OR we can do cart abandonment on the invoices with special status

**Comment by Stiofan** [comment]
I have tested the latest version of the form here https://ppldb.com/wpi/a-test1/

For payment input we don't want a extra step, so if for example a user has only one gateway active, lets say stripe, then no gateway options should show, only the stripe fields, basically the credit card fields.

If multiple gateways are set then it should show the options for gateways but also show the current selected gateway inputs and this is changed via ajax when gateway is changed.

**Comment by picocodes** [comment]
I think this is done
