### ISSUE TITLE
Possible to add Time AM/PM via Keyboard.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#299]
We can type the numbers for Hour and Minute, but can't type AM/PM..

Is this possible to add?

![image](https://user-images.githubusercontent.com/208945/81932519-8f397180-9609-11ea-83c3-fdf492a12fe1.png)

**Comment by picocodes** [comment]
Yeah. What browser are you on?

**Comment by laranz** [comment]
Google Chrome.

**Comment by picocodes** [comment]
We're using the native time HTML field which is fully supported in Chrome as far as I know. Try typing anything in the field after you enter the time and it will switch between AM and PM

**Comment by laranz** [comment]
@picocodes  If I type numbers after entering the time, it switch between AM/PM.. 

but didn't able to change the AM/PM after pressing the key A or P.
