### ISSUE TITLE
If one product is Recurring then the whole amount is recurring.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#301]
1. Daily Newspaper is the recurring item.
2. New Item! is not recurring.

But the total said, $66 is recurring.

![image](https://user-images.githubusercontent.com/208945/82015383-42eb4180-969c-11ea-805c-cb7e526b1ba4.png)

**Comment by picocodes** [comment]
Yeah, Invoicing allows checking out a single recurring item only. I'm going to add a notice that prevents admins from creating a form that allows users to check out several recurring items. In a future version though, checking out several recurring items will be possible.
