### ISSUE TITLE
Show/Hide buttons on Address Field.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#302]
When we click the Eye icon on the element to hide it, the element expands.. is this a feature or bug?

![image](https://user-images.githubusercontent.com/208945/82017662-48975600-96a1-11ea-9ad2-3e32e22760af.png)

**Comment by picocodes** [comment]
Initially, this was a feature. But I think it is not helpful, and misleading at the same time. I've fixed it.
