### ISSUE TITLE
Invoicing -> Items -> Add New active menu item disappear.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#307]
This happens for all the post type inside "Invoicing" Menu..

# 1. Go to Dashboard -> Invoicing -> Items.

![image](https://user-images.githubusercontent.com/208945/82036226-41327580-96be-11ea-9bda-cde898e36054.png)

# 2. Click Add New.

![image](https://user-images.githubusercontent.com/208945/82036292-5c9d8080-96be-11ea-9efb-8672715bf731.png)

# After that the Menu active gone.

**Comment by picocodes** [comment]
Fixed
