### ISSUE TITLE
Invoice -> Quotes.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#314]
![image](https://user-images.githubusercontent.com/208945/82048989-3c2bf100-96d3-11ea-95dc-117b111df1b0.png)

All the "Number" fields accepts "Strings".. ZIP CODE and VAT can be Alpha-numeric, so here only Phone number is the issue. :)

**Comment by picocodes** [comment]
See https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers
