### ISSUE TITLE
Invoice -> Quotes.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#315]
![image](https://user-images.githubusercontent.com/208945/82049337-c5432800-96d3-11ea-95da-cf7356bec053.png)

We can't add recurring items into the Quotes.. So can we prevent it from the list populated?

**Comment by picocodes** [comment]
Quotes actually support recurring items, but like invoices, you can only add a single recurring item to the quote. i.e, a quote cannot contain a recurring item together with any other item, (be it recurring or not)
