### ISSUE TITLE
Deleting Invoice -> Quotes -> Quote Items.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#318]
![image](https://user-images.githubusercontent.com/208945/82051099-e8230b80-96d6-11ea-95ba-9f4d687e83bf.png)

Deleting the quotes deletes 1 qty at a time..

For example, the first item we need to delete 3 times to delete it completely..

Bug or feature?

**Comment by picocodes** [comment]
It allows users to reduce item quantities without starting over.
