### ISSUE TITLE
Price variations per person/quantity

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#320]
An add-on that allows setting prices like these:

Example:

1 Person = $115
2 Person = $99 per person
+3 Person = $85 per person

If I select 1, the form will automatically calculate: $115
If I select 2, the form will automatically calculate: $198
If I select 5, the form will automatically calculate: $425

Or

100 T-shirts $15 per piece
500 T-shirts $13 per piece
+1000 T-shirts $10 per piece

**Comment by picocodes** [comment]
How should this be tackled?

**Comment by Stiofan** [comment]
@picocodes  I would think the best idea is to add a "Quantity discount" repeater field to the item page, thoughts?

**Comment by pol76** [comment]
@picocodes. We'll provide instructions on how to tackle this, leave this for later.
Thanks

**Comment by pol76** [comment]
an example of a classic user' request...
https://web.facebook.com/groups/elementorandwhichplugin/permalink/1185005678510387/

**Comment by pol76** [comment]
This is what I have in mind: https://woocommerce.com/products/tiered-pricing-table-for-woocommerce/

**Comment by pol76** [comment]
There is a free version that we can download and check how it works if needed: https://wordpress.org/plugins/tier-pricing-table/

**Comment by pol76** [comment]
https://github.com/AyeCode/wpinv-price-by-quantity
