### ISSUE TITLE
Yoast 14.1 breaking select2 style

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/invoicing#326]
sample code snippet
<img width="652" alt="Screenshot 2020-05-19 at 12 22 42 PM" src="https://user-images.githubusercontent.com/24760592/82294462-d2119580-99cb-11ea-9a33-416a24887e14.png">
 used for GD 

add_action( 'admin_enqueue_scripts', 'remove_default_stylesheet',99 );
function remove_default_stylesheet() {

	$screen         = get_current_screen();
	$screen_id      = $screen ? $screen->id : '';
	$geodir_map_name = GeoDir_Maps::active_map();
	$asdsadasd = geodir_get_screen_ids();
	
	if ( in_array( $screen_id, geodir_get_screen_ids() ) ) {
		wp_deregister_style( 'yoast-seo-select2' );
		wp_deregister_style( 'yoast-seo-monorepo' );
	}
}

**Comment by picocodes** [comment]
Thanks fixed
