### ISSUE TITLE
Upsells, Downsells and order bumps.

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#333]

**Comment by picocodes** [comment]
Is there an example?

**Comment by pol76** [comment]
Hi Brian,

there are several examples for WooCommerce: 

You can check the Cartflows website: https://cartflows.com/

There are a lot of videos to explain how Upsell, Downsell, and Order Bumps work.

For example:

Upsell / Downsell: https://www.youtube.com/watch?v=nG72h1tywuw&feature=emb_title

Order Bump: https://www.youtube.com/watch?v=5uxCyTnRDAw&feature=emb_title

There are also some free plugins on wp.org (I haven't tested them, but the concept is the same).

1) For Upsell / Downsell: https://wordpress.org/plugins/woo-one-click-upsell-funnel/ 

This is done after the checkout of the main product, so the sale is secured. If either the Upsell or Downsell are accepted, it uses token of the original purchase to complete the transaction. (won't be possible with all payment gateways, but many allow this) 

2) This is an example of a product bump plugin: https://wordpress.org/plugins/upsell-order-bump-offer-for-woocommerce/
This is a product that is offered on the check out page to compliment the purchase of the main product.  

Let me know if you have any questions. 

Thank you!

**Comment by pol76** [comment]
I was thinking we should add these fields on the add/edit item page and the add/edit form page:
 
1 Page to be used to offer the upsell [select a WP page] - (this is the page users will be sent to if the original item or form is purchased)
2 Item/form offered as upsell [select GP item or form] - (this is the item or form that if purchased will send users to the thank you page, if declined it will send the user to the down-sell page).  

3 Page to be used to offer the down-sell [select a WP page] - (this is the page users will be sent to if the upsell item is declined) 

4 Item/form to offer as down-sell [select GP item or form] - (this is the item that if purchased or declined will send users to the thank you page).

5 Page to be used as a Thank you page [select a WP page] - (if enabled, this is the custom thank you page for the funnel, if disabled, the default thank you page will be used). 

Each of these options has a checkbox to activate it, if not active, the step is skipped.

Let me know if you have any questions or doubts.

**Comment by picocodes** [comment]
I'm done with the order bumps.

As for upsales/downsales - Authorize.NET is our only gateway that uses payment tokens. I think it would be faster and easier to display the upsales/downsales on the order receipt page and when clicked, display a payment form in a modal.

**Comment by picocodes** [comment]
@pol76 Here is a screenshot of the order bumps.

![screenshot-localhost-2020 11 13-11_35_15](https://user-images.githubusercontent.com/19934448/99050070-b49f3c00-25a8-11eb-97e6-724ccdeed641.png)

Admins can change the title via **Settings > General > Label Texts**.

Clicking on the button adds/removes the item from the cart.

**Comment by picocodes** [comment]
https://github.com/AyeCode/getpaid-upsales-downsales-order-bumps/issues/1

@pol76 @laranz @sufyanism
