### ISSUE TITLE
GetPaid snaglist

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#337]
Very impressive @picocodes!

Couple of things to fix:

1 Remove "trash" for the default form here: https://ppldb.com/wpi/wp-admin/edit.php?post_type=wpi_payment_form

2 Find all wpinv_ strings and replace with gp_ (several here https://ppldb.com/wpi/wp-admin/admin.php?page=wpinv-settings)

@stiofan do we need payment notification in email settings? https://ppldb.com/wpi/wp-admin/admin.php?page=wpinv-settings&tab=emails

Thanks!

**Comment by picocodes** [comment]
thanks @pol76  fixed 1 and 2. For 2, I did not change the shortcodes as it would break backward-compatibility.

**Comment by Stiofan** [comment]
Feedback needed https://geodirectoryexperts.com/jobs/
