### ISSUE TITLE
Pricing table integration

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#357]
Make sure to integrate with the best in term of code quality: 

This is what our competitors integrate with https://wordpress.org/plugins/easy-pricing-tables

**Comment by picocodes** [comment]
@pol76 https://wordpress.org/plugins/easy-pricing-tables does not have any hooks that we can use to integrate with them. https://wordpress.org/plugins/pricing-table-by-supsystic/ does seem to have more active installs and might be a better fit.

**For now, I've added a feature in GetPaid that allows users to directly link to a form or item using a URL.**

### Example 1,

Using `#getpaid-item-2092|0` as a URL will load the default form where the user can buy item 2092. Item ids are separated by commas whereas pipes separate quantities.  Using zero as a quantity allows users to enter their own quantities. Leaving out the quantity assumes 1 as the quantity.

 `#getpaid-item-2092|0,2093` - This means that a user can enter their own quantity for item id 2092 but can only buy one of item 2093.

###  Example 2,

`#getpaid-form-35` - This will load the form with ID 35 in a modal.

This feature allows users to use GetPaid in any pricing table that does not have a native integration with GetPaid. All you have to do is specify #getpaid-form-35 as the URL of a button.

Here is an example https://ppldb.com/getpaid/pricing-table/ (https://ppldb.com/getpaid/wp-admin/post.php?post=127&action=edit)

@sufyanism  This might need documentation.

**Comment by picocodes** [comment]
Another example with supsystic https://ppldb.com/getpaid/susystic-pricing-table/ (https://ppldb.com/getpaid/wp-admin/admin.php?page=tables-supsystic&tab=tables_edit&id=8#main)

**Comment by pol76** [comment]
this looks good, thanks Brian!
