### ISSUE TITLE
Editing customer details

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#367]
Please add a new section about customers (mirroring user's info), where it is possible to edit all customer's details with all the (currently) missing fields.
See https://secure.helpscout.net/conversation/1213254499/4773/

Thanks

**Comment by pol76** [comment]
Brian, ask to Stiofan if you have any doubts about this... Thanks

**Comment by picocodes** [comment]
I've added a new admin page where admins can view customer details (and a link to edit the customer details).
