### ISSUE TITLE
Item must be editable

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#423]
Apparently, we had made items not editable because of a quirk in GD. 

This is potentially a dealbreaker that makes the GetPaid plugin less attractive than any competitor.  

We did not have separate data stored for the subscription info so we made them non-editable

Stiofan said he's pretty sure we do now have separate data stored for the subscription info so it should not be an issue.

Please make it possible to edit or delete existing items. 

Thanks

**Comment by picocodes** [comment]
By editable, do you mean on the invoice or the admin backend (as is the
case for listing packages )

**Comment by Stiofan** [comment]
We mean going into an item, the title, price and description are not editable.
![Screenshot from 2020-11-04 09-24-05](https://user-images.githubusercontent.com/10433311/98093247-97b78a00-1e7f-11eb-8e67-b120f4df8928.png)

**Comment by picocodes** [comment]
Changed here https://github.com/AyeCode/invoicing/pull/434
