### ISSUE TITLE
Add %price% variable to Pay Now Button text

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#424]
I like that "wp simply pay" has the price to be paid on the button.

![Capture](https://user-images.githubusercontent.com/25163253/98020315-78115a80-1dc8-11eb-9db8-fcc69ca0a158.JPG)

We should add a %price% variable that can be used in Button Text so that we can easily replicate that. The %price% variable should be added by default.

That way if cart details are hidden, the price is visible somewhere.

Thanks

**Comment by picocodes** [comment]
Done. New forms will automatically use Pay %price% as the button label.
