### ISSUE TITLE
item featured image

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#425]
please enable featured image and add an option to block/shortcode/widget to hide it or show it on top of the form or button.

This will be particularly useful for upsell / downsell / order bumps

An example should look like this: https://wpgeo.directory/getpaid/organic-coffee/

**Comment by picocodes** [comment]
The example page leads to a 404 page.

**Comment by Stiofan** [comment]
I think its now this one https://wpgeo.directory/getpaid/physical-product-optimized-form/

**Comment by pol76** [comment]
I'll make a new example of it ASAP.

Thanks

**Comment by picocodes** [comment]
Okay, I've enabled the featured images but I'm not sure how to go about displaying them. This is because the SuperDuper block allows users to add several items/products.

What's the best way to display the item images?

**Comment by Stiofan** [comment]
@pol76 maybe a slider or a gallery grid?

**Comment by pol76** [comment]
By default, I would simply add a picture at the top of the form and options for the admin to show/hide it. 

My main goal though is one day to be able to create forms with multiple items and pictures/prices. See this example of a Pizza order form here: https://pafe.piotnet.com/docs/repeater-fields-multi-level-nested/

Let me know if there are any doubts.

Thanks
