### ISSUE TITLE
Buy now button Card fields are not showing in lightbox

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#426]
the JS to insert it is not firing.

see https://wpgeo.directory/getpaid/productized-service/

We need to call the function after ajax load.

Thanks

**Comment by picocodes** [comment]
The site is probably not using the latest version of [our Stripe addon](https://github.com/AyeCode/wpinv-stripe-payment). It contains changes that add compatibility to GetPaid.

**Comment by pol76** [comment]
Ok I'll test that

**Comment by pol76** [comment]
tested and confirmed, it was the old add-on.

Thanks
