### ISSUE TITLE
Option in address field for Billing / shipping address

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#427]
Add an option in the address field for the Shipping / Billing address.

If enabled, whenever you add the address field, it should add a checkbox ticked by default saying: Same billing & shipping address.

 If unticked, a new set of Address fields show up to enter a different shipping address compared to the billing address.

**Example:** 
![image](https://user-images.githubusercontent.com/25163253/98024274-af363a80-1dcd-11eb-8a30-631162f4272b.png)

If the Shipping / Billing address option is enabled, it should also add a heading title to the set of Address fields saying:

If the check box is ticked:
**Billing / Shipping address** 

> Address fields here <

If the Check box is unticked:

**Billing address** 
 
> Billing Address fields here <

**Shipping address** 

> Shipping Address fields here <

Thanks

**Comment by picocodes** [comment]
I think we should postpone this until we start handling physical products. Or maybe include it as a feature in a "Physical Products" addon.

At the moment, we do not have any special handling for shipping fields so it might not be appropriate to collect shipping information on the frontend.

**Comment by pol76** [comment]
People who are shipping only to their own country can easily add a fixed shipping fee for all. 
Just FYI.

**Comment by Stiofan** [comment]
Here in the UK the main postage service "royal mail" charges by the size/weight, not the destination. Lets start basic with a fixed price and we can work on shipping calculator extension after.

**Comment by picocodes** [comment]
Hey,

I just pushed some shipping address changes [here.](https://github.com/AyeCode/invoicing/commit/c1377e44abc6b96b35c05b2f1ad18b639c5c1da4)

Kindly confirm in case I missed something.
