### ISSUE TITLE
Form elements styling options

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#428]
It would be great if we added some styling options to form elements.

For example, to change a little bit the format of this form, I had to use pseudo-classes. 

https://wpgeo.directory/getpaid/organic-coffee/

Most ppl don't know how to do these things. 

To improve this, we can:

1. add unique classes to the HTML of all elements.

That way people can style with CSS easily.

2. add some styling options to each element 

For example, see image:

![Capture](https://user-images.githubusercontent.com/25163253/98051897-706aa980-1dfa-11eb-8f48-a27ebf624636.JPG)

We could add there :

1. a select for Size with options: 1/1 - 1/2
2. a select for Float with options: none - left - right

That would have been enough for what I needed.

Thanks

**Comment by picocodes** [comment]
Thanks. I've added both the classes and the size selection. I've skipped the floats because bootstrap no longer uses floats. It uses "CSS flex " instead. Besides, the fields can be reordered.

**Comment by Stiofan** [comment]
Hi @picocodes Good work on this but there was a little misunderstanding, the task was to add this to the address fields not all the individual fields (although this is great to have also). Can you extend this size option to the individual address fields please.  The idea is we can do something like the image attached.
![Screenshot from 2020-11-04 17-03-20](https://user-images.githubusercontent.com/10433311/98142446-b63d7580-1ebf-11eb-89d7-73bd23ab55ef.png)

**Comment by pol76** [comment]
Hi Brian, 

Sorry for changing the URL of the example page, I'm sure it would have been easier to understand by seeing the example I made: https://wpgeo.directory/getpaid/physical-product-optimized-form/

**Comment by picocodes** [comment]
@Stiofan Sorry I forgot to mention it in the PR but there is a new field in each address "sub-field" that allows you to set the width of the address sub-field.

![screenshot-localhost-2020 11 04-20_16_59](https://user-images.githubusercontent.com/19934448/98146028-543f3900-1edc-11eb-96d5-c1bd85d8409a.png)


@pol76 Taking a look.

**Comment by Stiofan** [comment]
OH! It seems we both completely missed that, awesome! :)

**Comment by pol76** [comment]
Excellent, I totally missed it! Thanks Brian
