### ISSUE TITLE
Overlapping select2 css

### ISSUE THREAD

**Issue by dhimaskirana** [AyeCode/invoicing#430]
Hi, I'm very glad to use this plugin. Thanks for the plugin.

But I found a bug that makes the admin page horizontal scrolling. It caused because the **select2-hidden-accessible** class have a width of 1px !important, but is replaced by the **gdmbx2-text-large** class with having a width 100% !important.

**The gdmbx2-text-large class**
<img width="329" alt="Screen Shot 2020-11-04 at 7 33 33 AM" src="https://user-images.githubusercontent.com/5303741/98055454-14426c80-1e70-11eb-9f39-706bf4b26742.png">

**The admin page**
<img width="974" alt="Screen Shot 2020-11-04 at 7 27 09 AM" src="https://user-images.githubusercontent.com/5303741/98055412-fa088e80-1e6f-11eb-89f0-c500579dce69.png">

**Comment by dhimaskirana** [comment]
I think just remove **!important** from the **gdmbx2-text-large** class will solve the issue.

**Comment by picocodes** [comment]
Thanks @dhimaskirana  This has been fixed for the upcoming release.
