### ISSUE TITLE
price in button doesn't update if i change quantity

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#436]

**Comment by picocodes** [comment]
I've taken a look at the form's shortcode and it appears like you have hardcoded the price instead of using the %price% variable.

![screenshot-pay-button](https://user-images.githubusercontent.com/19934448/98226811-995c7d00-1f67-11eb-9f32-77cdfa4ac2a6.jpg)

**Comment by pol76** [comment]
You are right, my bad. Sorry about that.
