### ISSUE TITLE
wpinv_mail_content Filter is not exist in new version of Get Paid Plugin

### ISSUE THREAD

**Issue by routesdevsupport** [AyeCode/invoicing#441]
Hi,

In latest get paid plugin. It would be good if we have an filter to modify the email content. We were the same in the old plugin but not in the latest get_paid plugin.

Old Filter: wpinv_mail_content
https://github.com/AyeCode/invoicing/blob/9470c1d07540c09ab8a6b2464a69ba4103b85438/includes/wpinv-email-functions.php#L632

Can you please add this filter in the new version of get_paid so we can use it?

Thank You

**Comment by picocodes** [comment]
Hey @routesdevsupport 

I've re-added the filter [here](https://github.com/AyeCode/invoicing/blob/c1377e44abc6b96b35c05b2f1ad18b639c5c1da4/includes/class-getpaid-notification-email-sender.php#L45).

**Comment by routesdevsupport** [comment]
Hello @picocodes 

Thank you very much..
