### ISSUE TITLE
Multisite Domain Change

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#467]
Things need to be changed on our sales site for GP launch.
- [x] Change site domain
- [x] Update Colours and design
- [x] Update theme checks for new domain
- [x] Update redirects plugin domain
- [x] Check plugin update checks still work
- [x] Update name on all site settings
- [x] Add rebranding notice if user is redirected from WPI domain

**Comment by basantaux** [comment]
![wpgetpaid-website-homepage](https://user-images.githubusercontent.com/52257358/104333920-c43ef080-5517-11eb-98f2-91031696e51e.png)

**Comment by basantaux** [comment]
![website-logo](https://user-images.githubusercontent.com/52257358/104335398-5b587800-5519-11eb-84be-523956e6f8d0.png)
![developer](https://user-images.githubusercontent.com/52257358/104335405-5c89a500-5519-11eb-92ae-257dbc7a7524.png)
![contact-form-7-logo@2x](https://user-images.githubusercontent.com/52257358/104335418-5dbad200-5519-11eb-9327-493bca39e94f.png)
![affiliatewp-logo](https://user-images.githubusercontent.com/52257358/104335422-5e536880-5519-11eb-98b4-409ae0be3bef.png)
![gravity-forms-2019-logo-horizontal svg-1](https://user-images.githubusercontent.com/52257358/104335426-5eebff00-5519-11eb-8573-05bc565f3121.png)
![ninja-forms](https://user-images.githubusercontent.com/52257358/104335428-5eebff00-5519-11eb-9a54-d839e04fa690.png)
![payment_bill](https://user-images.githubusercontent.com/52257358/104335430-5f849580-5519-11eb-8930-973b5b9c3120.png)
![form-integration](https://user-images.githubusercontent.com/52257358/104335434-601d2c00-5519-11eb-8309-98a76a8700a1.png)
![payment](https://user-images.githubusercontent.com/52257358/104335437-601d2c00-5519-11eb-8ce5-fef29ef02cb0.png)
![quote-icon](https://user-images.githubusercontent.com/52257358/104335440-60b5c280-5519-11eb-882c-fa685f93d0b3.png)
![tax-icon](https://user-images.githubusercontent.com/52257358/104335443-614e5900-5519-11eb-9c7f-07bd9932908c.png)
![form-list-bg](https://user-images.githubusercontent.com/52257358/104335447-61e6ef80-5519-11eb-8e72-fea17cf5a194.png)
![form-list](https://user-images.githubusercontent.com/52257358/104335450-627f8600-5519-11eb-83c4-06fe184534dd.png)
![form-bg](https://user-images.githubusercontent.com/52257358/104335451-63181c80-5519-11eb-873a-e2594d05494d.png)
![payment-form](https://user-images.githubusercontent.com/52257358/104335452-63b0b300-5519-11eb-8739-1ac131ef3f0c.png)
![e-book](https://user-images.githubusercontent.com/52257358/104335456-63b0b300-5519-11eb-9122-96b5bc3de9c1.png)
![payment-button](https://user-images.githubusercontent.com/52257358/104335457-64494980-5519-11eb-846c-44fa61e002f5.png)
![dash-board](https://user-images.githubusercontent.com/52257358/104335459-64e1e000-5519-11eb-9fdb-16ea85b35a7e.png)
![payment-logo](https://user-images.githubusercontent.com/52257358/104335462-657a7680-5519-11eb-847f-4a3a854145a3.png)
![web-hero](https://user-images.githubusercontent.com/52257358/104335465-657a7680-5519-11eb-81dd-85d32c135c47.png)
