### ISSUE TITLE
Icon and Banner Images

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#471]
We need icons and banner images for the following, please upload or link to them in the comments.

- [ ] WordPress Plugin page
- [ ] Facebook
- [ ] Twitter

**Comment by basantaux** [comment]
![twitter-head](https://user-images.githubusercontent.com/52257358/104331874-9a84ca00-5515-11eb-842a-333cfd2723b9.png)
![facebook-head](https://user-images.githubusercontent.com/52257358/104331891-9e185100-5515-11eb-9e3d-b2ef94e1062f.png)
![icon-256](https://user-images.githubusercontent.com/52257358/104331892-9eb0e780-5515-11eb-8449-272b500b274f.png)
![banner-1544x500](https://user-images.githubusercontent.com/52257358/104331893-9f497e00-5515-11eb-905e-0d4dbc8d6576.png)
![icon-128](https://user-images.githubusercontent.com/52257358/104331896-9fe21480-5515-11eb-8048-0ab1755bc79e.png)
![banner-772x250](https://user-images.githubusercontent.com/52257358/104331898-9fe21480-5515-11eb-910b-f10e9a63d9d3.png)

**Comment by basantaux** [comment]
Please check and let me know

**Comment by Stiofan** [comment]
@pol76 please approve or ask for any changes.

**Comment by Stiofan** [comment]
Hi @basantaux can you have another bash at this, i don't think either of us particularly likes this, especially the orange bits.

I also think we should have the text 
"GetPaid via:
    Buy Now Buttons
    Custom Payment Forms
    Invoice"

**Comment by basantaux** [comment]
![twitter-head](https://user-images.githubusercontent.com/52257358/104358954-1f331080-5535-11eb-99a9-6b354ba4efdb.png)
![facebook-head](https://user-images.githubusercontent.com/52257358/104358969-22c69780-5535-11eb-9593-eb674847c3fc.png)
![banner-772x250](https://user-images.githubusercontent.com/52257358/104358977-24905b00-5535-11eb-9783-1a47db175110.png)
![banner-1544x500](https://user-images.githubusercontent.com/52257358/104358981-25c18800-5535-11eb-89ef-785185fdcd5c.png)

**Comment by basantaux** [comment]
please check now

**Comment by pol76** [comment]
This is a lot better. I like them, let's see what @Stiofan says.
Thanks @basantaux !

**Comment by picocodes** [comment]
@basantaux @Stiofan @pol76 I think "invoices" is a little better than "invoice"

**Comment by Stiofan** [comment]
@basantaux yeah @picocodes is right, lets go with "Invoices"

**Comment by basantaux** [comment]
![twitter-head](https://user-images.githubusercontent.com/52257358/104435338-47ad2000-55b2-11eb-9984-f958777c988b.png)
![facebook-head](https://user-images.githubusercontent.com/52257358/104435353-4b40a700-55b2-11eb-9138-7c7b2dd67f06.png)
![banner-1544x500](https://user-images.githubusercontent.com/52257358/104435356-4bd93d80-55b2-11eb-98f6-6c30f80d23f9.png)
![banner-772x250](https://user-images.githubusercontent.com/52257358/104435357-4c71d400-55b2-11eb-8c50-eb3d733153a8.png)

**Comment by basantaux** [comment]
done
