### ISSUE TITLE
New wp.org screenshots

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#474]
We need some new wp.org screenshots, can you provide these?

**Comment by basantaux** [comment]
![crowdfunding](https://user-images.githubusercontent.com/52257358/104907898-c2f44480-59ab-11eb-9295-6e8b5bcfc6eb.jpg)
![Report](https://user-images.githubusercontent.com/52257358/104907912-c5569e80-59ab-11eb-91dc-f411f4106b35.jpg)
![Subscription](https://user-images.githubusercontent.com/52257358/104907915-c5ef3500-59ab-11eb-80f2-ba6f74d2d185.jpg)
![payment-forms](https://user-images.githubusercontent.com/52257358/104907919-c687cb80-59ab-11eb-935d-312b17183a75.jpg)
![donations](https://user-images.githubusercontent.com/52257358/104907922-c7b8f880-59ab-11eb-9f3a-6c86fc55f753.jpg)
![digital-product](https://user-images.githubusercontent.com/52257358/104907924-c8518f00-59ab-11eb-9c13-a0b2c50f15d2.jpg)
![product-service](https://user-images.githubusercontent.com/52257358/104907926-c8518f00-59ab-11eb-90b6-7e9881bc88bd.jpg)

**Comment by picocodes** [comment]
@basantaux Kindly add one for the invoice view page and another for the payment receipt page

**Comment by picocodes** [comment]
Also another for form/invoice/item/discount edit pages.

**Comment by basantaux** [comment]
![INVOICE-EDIT](https://user-images.githubusercontent.com/52257358/104910337-2df34a80-59af-11eb-96b9-36844a6301a2.jpg)
![INVOICE-VIEW](https://user-images.githubusercontent.com/52257358/104910340-2fbd0e00-59af-11eb-9d9b-73ab09d917c6.jpg)
