### ISSUE TITLE
Paid Claim not working with latest

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/invoicing#485]
**Describe the bug**
paid claim submission skips payment
AC not working

weird behavior with gd https://secure.helpscout.net/conversation/1401657423/13500/

**Comment by Stiofan** [comment]
@kprajapatii please confirm issue on a test site, if its a bug please assign to brian.

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodir_payment_manager-v3/commit/c9b215e00c883f371c4a67bcfeaa04678d78dd26
