### ISSUE TITLE
Invoices not showing tax based on address

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#493]
https://secure.helpscout.net/conversation/1351436130/11155/

Invoices both in the backend and when viewing do not show tax at all. This should show based on the invoice address. 
(tax is showing correctly on checkout)
https://ppldb.com/stiofan/wp-admin/post.php?post=4874&action=edit

**Comment by picocodes** [comment]
This has been fixed here https://github.com/AyeCode/invoicing/commit/37ef0bdb156631a39e9e51e04a7dd1e590ba6598

**Comment by Stiofan** [comment]
testing
