### ISSUE TITLE
Stop sending the form to server when the user enter the item price less than the minimum item price.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#497]
Stop sending the form to server when the user enter the item price less than the minimum item price.

![image](https://user-images.githubusercontent.com/208945/105756216-53b1be00-5f72-11eb-8a6f-17af3372a1ee.png)

Steps to recreate:
1. Create an item, and choose "Let customers name their price" option, and then choose a minimum value.
2. Now in the front-end, choose a value less than the minimum price, We provide an instant error message like "The minimum allowed amount is 5" now hit "Pay now" button, 
3. It post to the server and fails back.
4. Instead we can disable the pay now button or stops sending the request to the server.

**Comment by picocodes** [comment]
Updated
