### ISSUE TITLE
SELECT2 problem reported by SliceWP developers

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#500]
**Describe the bug**
found a small select2 conflict between GetPaid and SliceWP while testing. I believe you're adding some custom styling for select2, we do this as well, and it seems yours is being loaded on all admin pages.

See screenshot for clarity
![Select2_bug](https://user-images.githubusercontent.com/25163253/106528591-9dd4fb00-64ae-11eb-9275-a3062d870749.JPG)

@stiofan, shouldn't we load our custom backend styles, only for our own admin pages?

Thanks for fixing this ASAP.

**Comment by picocodes** [comment]
@Stiofan I believe we should default to loading aui styles only if aui() is called. Though this will mean loading the styles in the footer and might lead to some flashes of unstyled content while the page is loading. Plugins that use aui() can then override this filter in a hook to load aui() in the header for their own custom pages.

**Comment by Stiofan** [comment]
This change has been added to AUI. We will need to sync the next releases of core products for this as otherwise it may break settings pages for 1 of the core products.  We should be able to get this out next week.
