### ISSUE TITLE
Payment fail or payment method missing email

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#505]
If a payment fails or if a payment method is missing we need to send the customer an email asking them to update their card details. Maybe this should be two different emails? (lets discuss)

The email should provide a link to be able to directly add a new card.  I think having to login could be a road block here, maybe we need to provide a direct link where this can be done without the need to login if this is set in settings? (lets discuss)

**Comment by picocodes** [comment]
Done
