### ISSUE TITLE
Add webhook script running on every page load.

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#506]
- Check if it fails, set a flag, ask for more permission (needs reconnect?)
- Can we currently read webhooks with current permissions? if so add a admin notice stating its missing.
- if so show a X or a tick next to the webhook setting

**Comment by picocodes** [comment]
Fixed in https://github.com/AyeCode/wpinv-stripe-payment/commit/c271f29accbdd018f976c5100bf9113ee6722a58
