### ISSUE TITLE
City not displaying on the Invoice Address metabox.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing#508]
![image](https://user-images.githubusercontent.com/208945/107087648-c3049900-6821-11eb-8641-bbd4781a45cb.png)

here: https://github.com/AyeCode/invoicing/blob/master/includes/admin/meta-boxes/class-getpaid-meta-box-invoice-address.php#L192

it gets the VAT number instead the get_city

**Comment by picocodes** [comment]
Nice fixed
