### ISSUE TITLE
Bug Scrub From Customer

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#532]
https://secure.helpscout.net/conversation/1405400739/13721?folderId=3817579
- [x] Subscription payments that used a discount code, renewals showing non discounted price (stripe charged correct discounted price)
- [x] Cancel subscription email (maybe all or more) when edited does not send the edited message but the default.
- [x] Listing expire tool did not expire listings. @kprajapatii 
- [x] GD, paid listing status if pending review set then renewals set listing to pending review. (lets discuss, i think this should not apply if already published) @kprajapatii

**Comment by kprajapatii** [comment]
3) Listing expire tool do not expire recurring listings. Recurring recurring listings only expired when subscription is cancelled or completed.

4) Fixed. https://github.com/AyeCode/geodir_payment_manager-v3/pull/140/commits/ce0133c1ce39e07cd0d728629d3291215d103799
If listing is published then it will set post status to publish on renew, no matter what paid listing status is set for package.

**Comment by picocodes** [comment]
Fixed #1 [here](https://github.com/AyeCode/invoicing/commit/52a8ae2e22260cd7d9481c3e8eaa19307e95ae62), #2 has been fixed [here](https://github.com/AyeCode/invoicing/commit/82bd211697b80b99a26ec77681f1fe9bfacdf378), plus [a tool to recalculate discounts for existing invoices that have discount codes but have not been discounted](https://github.com/AyeCode/invoicing/commit/0587d754d6ae6c0b8155663c1d004c6bb5269f30).

**Comment by picocodes** [comment]
Fixed #1 [here](https://github.com/AyeCode/invoicing/commit/52a8ae2e22260cd7d9481c3e8eaa19307e95ae62), #2 has been fixed [here](https://github.com/AyeCode/invoicing/commit/82bd211697b80b99a26ec77681f1fe9bfacdf378), plus [a tool to recalculate discounts for existing invoices that have discount codes but have not been discounted](https://github.com/AyeCode/invoicing/commit/0587d754d6ae6c0b8155663c1d004c6bb5269f30).
