### ISSUE TITLE
invoice not sent on saving 

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#545]
**Describe the bug**
When you save the invoice, only an email instruction to register is sent. No invoice is sent. 

I remember in a previous version there was a checkbox above the save button asking if the invoice needed to be sent on save, why is it no longer there? Why is the invoice not sent?

Thanks for letting me know asap. We have a ticket about this.

**Comment by pol76** [comment]
Ticket https://secure.helpscout.net/conversation/1450742821/16198/

**Comment by picocodes** [comment]
This has been fixed here https://github.com/AyeCode/invoicing/commit/bc0413cae549069992b28953a722a9c54a6c1ac2 for the next update. The email (if enabled in settings) was supposed to be automatically sent new invoices.

**Comment by pol76** [comment]
Hi Brian,

I'm not sure how this is done now, but either we add the option to save the invoice as a draft, or I think it's better to add the option as it was before (checkbox to enable sending an invoice on save).

See this user comment about this: https://secure.helpscout.net/conversation/1453993877/16364/

Thanks,

**Comment by picocodes** [comment]
I've readded the checkbox. So now the invoice is only emailed if the checkbox is checked (regardless of whether the email is enabled or not). If the email is enabled, the checkbox is auto-checked for draft invoices.

**Comment by picocodes** [comment]
There is also a draft option in the Invoice statuses dropdown. No emails are sent if an invoice is in draft mode.
