### ISSUE TITLE
Tutorial for custom payment gateways

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#546]
Hi @picocodes,

can you please confirm if this is still valid: https://wpgetpaid.com/docs/developers/creating-a-payment-gateway/

If not, can you please edit it once you have the time?

@sufyanism we'll need to add this to docs once we have Brian's green light.

Thanks

**Comment by picocodes** [comment]
It needs a few changes, we'll update it later

**Comment by sufyanism** [comment]
Will wait to hear from Brian before adding to new docs.

**Comment by Stiofan** [comment]
Lets get these moved over to the new docs site, then we can take the old docs site down.

**Comment by picocodes** [comment]
Updated here https://docs.wpgetpaid.com/article/550-creating-a-payment-gateway
