### ISSUE TITLE
Style issue on add item page

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/invoicing#547]
**Describe the bug**
the label goes on the new line and in the sidebar, it overflows. 

**Expected behavior**
the label should be beside the help tip icon

**Screenshots**
<img width="1512" alt="Screenshot 2021-03-12 at 8 02 02 AM" src="https://user-images.githubusercontent.com/24760592/110883576-b46e3d80-8309-11eb-9cbe-3df11c874b27.png">

**Desktop (please complete the following information):**
 - OS: OSX 
 - Browser: chrome, safari
 - Version: Master branch

**Comment by picocodes** [comment]
What theme are you using? Is there another bootstrap plugin on the site? Also check if bootstrap is loading on the page.

**Comment by sandeepjain2015** [comment]
@here @picocodes this is coming due to full mode css

![AyeCode UI ‹ t](https://user-images.githubusercontent.com/14997279/112476041-7b1cdf80-8d97-11eb-8429-0fd9980fdb5d.png)
