### ISSUE TITLE
Unable to disable VAT NUMBER field

### ISSUE THREAD

**Issue by sridhargoshika** [AyeCode/invoicing#552]
I am trying to disable VAT Number field from the checkout page and admin add new invoice page.

**Comment by picocodes** [comment]
You can disable it from the checkout by [removing it from your payment forms](https://docs.wpgetpaid.com/article/400-how-to-add-a-payment-form).

At the moment, the only way to remove it from the admin page is by hiding it with CSS, though we're working on a better way to handle this.
