### ISSUE TITLE
Setup wizard screen design

### ISSUE THREAD

**Issue by basantaux** [AyeCode/invoicing#565]
Design screen for setup wizard

**Comment by basantaux** [comment]
![finish-setup](https://user-images.githubusercontent.com/52257358/114596089-cea28f00-9cac-11eb-9490-bfc852906967.png)
![page-setting](https://user-images.githubusercontent.com/52257358/114596098-d19d7f80-9cac-11eb-866d-03b926bbaae9.png)
![gateway-setting](https://user-images.githubusercontent.com/52257358/114596100-d2361600-9cac-11eb-8efb-0e7ad8243245.png)
![currency-settings](https://user-images.githubusercontent.com/52257358/114596102-d2ceac80-9cac-11eb-836f-f30f7267465a.png)
![general-settings](https://user-images.githubusercontent.com/52257358/114596105-d3674300-9cac-11eb-9d93-4b196b1a2ba1.png)
![start](https://user-images.githubusercontent.com/52257358/114596107-d3ffd980-9cac-11eb-8f45-055530d714b6.png)

**Comment by pol76** [comment]
Looks great! Thanks @basantaux
