### ISSUE TITLE
Settings reset on plugin upgrade

### ISSUE THREAD

**Issue by compito** [AyeCode/invoicing#567]
This has happened several times we updated the plugin. 
It's really bad because suddenly we don't have any payment gateways, and also we have to set up everything again. It's bad enough in test environment, but unacceptable when we go live with the project.

**To Reproduce**
Go to updates page in WP when there is one and update the plugin. Go to GetPaid settings, and all the gateways are disabled, tax settings are gone, all setup settings are lost.

**Expected behavior**
All settings for our accounts (Stripe etc), tax settings, have to be saved and restored on plugin update.
We can't use it this way in production environment, obviously.

**Comment by compito** [comment]
One setting is actually saved, the Tax Rate. We have one of those set up for Sweden and it's the only thing that we still have after the update.

**Comment by Stiofan** [comment]
Hello,

I see your support ticket and i have replied, lets continue there.
