### ISSUE TITLE
Disable emails check

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#575]
User reports that even when "on-hold" email is disabled it still sends https://secure.helpscout.net/conversation/1484217024/17818?folderId=3817579

**Comment by picocodes** [comment]
I'm unable to reproduce this. @laranz please test on your end.

**Comment by laranz** [comment]
@Stiofan  if I disable the ON-HOLD email, then it didn't send any email. Maybe he uses any old version where this bug exists? @picocodes
