### ISSUE TITLE
User payment form fields as merge tags

### ISSUE THREAD

**Issue by picocodes** [AyeCode/invoicing#578]
**Is your feature request related to a problem? Please describe.**
It seems there are no merge tags for payment form elements.

**Describe the solution you'd like**
Ad a way to use form element ids as merge tags.

https://secure.helpscout.net/conversation/1493784218/18283

**Comment by sridhargoshika** [comment]
I have included payment form fields by overriding the template file `yourtheme/invoicing/invoice/invoice-meta.php` 
Here is my code,
` <table class="table table-bordered">
                <tbody>
                <?php
                    $payment_form=get_post_meta( $invoice->get_id(), 'payment_form_data', true );
                    if($payment_form){        
                        foreach ($payment_form as $key => $value) {
                            ?>
                            <tr>
                            <th><?php echo $key; ?></th>
                            <td><?php echo $value;?></td>
                            </tr>
                            <?php
                            }        
                        }
                ?>
                    <?php do_action( "getpaid_before_invoice_meta_rows", $invoice ); ?>`

**Comment by picocodes** [comment]
For emails, this has been addressed here https://github.com/AyeCode/invoicing/commit/f2724257001fdb18bb6f6c48f49acf11a98b5a71
