### ISSUE TITLE
Create new item while adding new invoice generates error

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#58]
There is an error in code when we add new item from add invoice interface.

1. Click on Create new item button.
2. Enter Item name, price, qty, type.
3. Click on save button to save the item.

It will display loading all the time as there is an error in the code but the item is added.

Screenshot:
![create new item gives error](https://user-images.githubusercontent.com/22492841/29171641-d11423fe-7dfa-11e7-94a8-c8aaa7105599.png)

Suggestions for Add item interface:
1. Form tab index need to be proper
2. If you click on white space in line with the buttons it will fire the save button which is not good. The button should be clicked only if we click on the button.
3. When we click on cancel all data should be erased from add item form.

**Comment by wpdev10** [comment]
Main issue is already fixed and we have PR for suggestion point no. 3

**Comment by wpdev10** [comment]
PR merged offline while testing the whole plugin. So closing this issue.
