### ISSUE TITLE
Create documentaion

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#59]
1. Explain each invoice status in detail. 
2. List all hooks that can be used for payments
3. Show how to use each main function for invoices, create, add items remove items etc.

**Comment by kprajapatii** [comment]
1) About Statuses Edit     - https://wpinvoicing.com/docs/wp-admin/post.php?post=91&action=edit
About Statuses Preview  - https://wpinvoicing.com/docs/?p=91&preview=true

Create & update item:
Create Item Edit        - https://wpinvoicing.com/docs/wp-admin/post.php?post=97&action=edit
Create Item Preview     - https://wpinvoicing.com/docs/?p=97&preview=true
Update Item Edit        - https://wpinvoicing.com/docs/wp-admin/post.php?post=98&action=edit
Update Item Preview     - https://wpinvoicing.com/docs/?p=98&preview=true
