### ISSUE TITLE
Docs Needed - PayPal Standard vs PayPal pro

### ISSUE THREAD

**Issue by picocodes** [AyeCode/invoicing#591]
https://wordpress.org/support/topic/paypal-pro-9/#post-14484083

**Comment by sufyanism** [comment]
https://docs.wpgetpaid.com/article/570-difference-between-paypal-standard-paypal-pro-and-paypal-payflow?auth=true 
Interlinked docs
https://docs.wpgetpaid.com/article/427-paypal-standard#paypal-standard 
https://docs.wpgetpaid.com/article/419-paypal-pro#paypal-payments-pro

**Comment by picocodes** [comment]
Thanks
