### ISSUE TITLE
Doc Request

### ISSUE THREAD

**Issue by picocodes** [AyeCode/invoicing#593]
https://wordpress.org/support/topic/item-for-subscriptions/

**Comment by wpdev10** [comment]
@sufyanism We need a doc for how to override the templates of GP in the theme.

**Comment by sufyanism** [comment]
@wpdev10 Can you clarify? Are you talking about replacing strings with Loco, as is shown in the ticket or something else?

**Comment by wpdev10** [comment]
I am talking about overriding templates in the theme. Like we do in UWP https://userswp.io/docs/developers/override-templates/

**Comment by sufyanism** [comment]
Rough Draft of steps

1. Copy the template you want to change, say for example: wpinv-invoice-print.php -- copy it from /invoicing/wpinv-invoice-print.php to a folder in your theme called theme/invoicing/wpinv-invoice-print.php

2. From here you can edit the template without having to edit the main files. 

@Stiofan @picocodes Can you confirm if the path slug is gonna be /invoicing/ or /getpaid/ ?

**Comment by picocodes** [comment]
Yes use invoicing

**Comment by sufyanism** [comment]
https://docs.wpgetpaid.com/article/582-how-to-override-getpaid-templates-in-themes?auth=true

**Comment by wpdev10** [comment]
Need correction for "copy it from /invoicing/wpinv-invoice-print.php"
Change it to "copy it from /invoicing/templates/wpinv-invoice-print.php"

**Comment by sufyanism** [comment]
Done
