### ISSUE TITLE
Create a doc on REST API and also how to create invoice programmatically

### ISSUE THREAD

**Issue by wpdev10** [AyeCode/invoicing#598]
Support ticket https://secure.helpscout.net/conversation/1531722879/20164?folderId=3817573

**Comment by wpdev10** [comment]
Here is the old doc https://wpgetpaid.com/docs/developers/wpinv_insert_invoice/ for your reference.

**Comment by joshfromdallas** [comment]
Thanks, I am interested in this also. I am able to create the invoice using php script but unable to create the line items, or figure it out. I would like to add an item and price to invoice when I create it.

**Comment by sufyanism** [comment]
https://docs.wpgetpaid.com/article/584-how-to-create-an-invoice-programmatically?auth=true
