### ISSUE TITLE
Suggestion: Add settings to enable/disable/change watermark in receipt

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#60]
Right now when the invoice is paid/cancelled it displays the watermark in the receipt. We can provide settings to enable/disable watermark and also input text to change the text of watermark.

Screenshot:
![watermark in receipt](https://user-images.githubusercontent.com/22492841/29173506-22589f32-7e01-11e7-8032-90e0f0924e93.png)

**Comment by wpdev10** [comment]
We have already provided filter "wpinv_get_watermark" to modify the text. So no need to add settings.
