### ISSUE TITLE
Paid Trial

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/invoicing#609]
**Is your feature request related to a problem? Please describe.**
Free trials are great, but members want paid trials, too.

**Describe the solution you'd like**
$15 for 5 months, then 99.99 monthly, thereafter, with stripe.

https://secure.helpscout.net/conversation/1552055319/21147/

**Comment by picocodes** [comment]
We have an unreleased extension for that https://github.com/AyeCode/getpaid-paid-trials

**Comment by pol76** [comment]
That's already developed and currently being tested: https://github.com/AyeCode/getpaid-paid-trials/
