### ISSUE TITLE
Suggestion: Display only active payment gateways

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#61]
Right now all the payment gateways are displayed in Payment gateways field. But there should be only active payment gateways displayed which are enabled from their respective settings tabs or we can remove the enable/disable setting for each individual payment gateways.

Screenshot:
![display only active payment gateways](https://user-images.githubusercontent.com/22492841/29173715-d38ceba0-7e01-11e7-9202-459fbc51ca7c.png)

**Comment by wpdev10** [comment]
Not required.
