### ISSUE TITLE
Form field IDs changing after every refresh make it impossible to write a JS script

### ISSUE THREAD

**Issue by pol76** [AyeCode/invoicing#610]
We need fixed ids in form fields.

I'm trying to write a javascript snippet to interact with the form data and I can't because after every refresh the field IDs are changed making the script useless.

For example, here the IDs of the Start and End date fields change after every page refresh. https://greenlagoonsurfing.com/book-surf-lessons/
 
It would be great if we had an option to add the field label as the field ID.

Thanks,

**Comment by picocodes** [comment]
is it possible to use css classes instead of ids in your JS? If we used fixed ids then users will not be able to add the same form twice on a single page.

**Comment by picocodes** [comment]
In your case you can select the number of people field using the name attribute as that never changes.

```
jQuery('input[name="kkcpjtmsg"' );
```

Though I've also made some changes to convert the label into a class name to make such selections easier.
