### ISSUE TITLE
Discount not working properly

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#65]
I have created a discount code with min. amount of $20 and max amount of $50. 
Screenshot:
![discount code](https://user-images.githubusercontent.com/22492841/29201100-e62e62a8-7e78-11e7-83d3-f7f508cc663d.png)

Steps:

Case-1:
1. Create a new invoice.
2. Add items having a price more than $20.
3. Apply the discount code.
4. Remove the item to decrease the total up to min. amount of discount code.
5. The discount should be automatically removed as the amount is not matching the conditions but it is saved with the applied discount code.

Screenshot:
![discount not working properly](https://user-images.githubusercontent.com/22492841/29200660-b05eb87a-7e74-11e7-8de8-a30e52623d4f.png)

Case-2:
1. Create a new invoice.
2. Add items which are allowed for discount and then add an item which is restricted for this discount.
3. Apply the discount code.
4. Remove the item which was allowed and keep only the restricted item.
5. The discount is removed from the items but not removed from discount code input field. We need to refresh the page to see the change.

Screenshot:
![discount removed from item but not affected at discount code](https://user-images.githubusercontent.com/22492841/29201004-db95384a-7e77-11e7-93d4-b08162284bf8.png)

Case-3:
1. Create a new invoice.
2. Add items which are restricted for this discount.
3. Apply the discount code.
4. It shows the wrong error message.

Screenshot:
![message is not proper for discount code](https://user-images.githubusercontent.com/22492841/29201047-59cc5c84-7e78-11e7-8616-6e0188b9edde.png)

Case-4:
1. Create a new invoice with the new user account.
2. Add items for the invoice
3. Apply the discount code with restrictions of "Use once per user" and is already applied to invoices for other user accounts.
4. It shows the error message as it should be applied.

Screenshot:
![single use per user discount](https://user-images.githubusercontent.com/22492841/29201422-bb9541b2-7e7b-11e7-8277-d758a98951a9.png)

Design issue when displaying an error message on the front side.
Screenshot:
![discount code front error](https://user-images.githubusercontent.com/22492841/29202567-19282d34-7e87-11e7-8214-3f3fc3338193.png)

**Comment by picocodes** [comment]
Only PayPal supports specifying 3 different amounts. Charging two different amounts can be achieved by offering a non-recurring discount or using the new paid trials addon.
