### ISSUE TITLE
Suggestion: Display tax for previous invoice if tax is disabled later

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#67]
If we enable tax and create invoices then it will display tax amount in invoice items. But later on, if we disable the tax then admin will not able to get why the total is different even no discounts applied as the tax values are hidden. So the tax values should be displayed if any even if the tax is disabled.

Screenshot:
![no tax if disable invoice](https://user-images.githubusercontent.com/22492841/29205489-ea1a9c16-7e9a-11e7-9a6b-e284e83d7442.png)

**Comment by Stiofan** [comment]
this is only a problem is it happens on the print invoice screen?

**Comment by mdrahul** [comment]
Yes it is there at admin side and print invoice screen both.

**Comment by wpdev10** [comment]
PR merged offline while testing the whole plugin. So closing this issue.
