### ISSUE TITLE
Upgrade Version 2.6.8 checkout not working for Authorize.Net payment gateway.

### ISSUE THREAD

**Issue by sridhargoshika** [AyeCode/invoicing#693]
I am getting the following error after upgrading the plugin to latest version 2.6.8. The earlier version worked.

**The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:expirationDate' element is invalid - The value XXXXXXXXXXXX is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value.**

I used the Authorize.Net payment method. It seems the expiry month and year dropdown's value property are not rendering.

**Comment by picocodes** [comment]
Hi please install the new update.
