### ISSUE TITLE
Resend Invoice displays wrong message if customer invoice email setting is disabled

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#71]
1. Disable Customer Invoice email notification setting.
2. Click on Resend invoice. It shows wrong error message as it should be related to the customer invoice email is disabled or the resend invoice button should be hidden.

Need your inputs.

Screenshots:
![resend invoice 2](https://user-images.githubusercontent.com/22492841/29399627-933a64ba-8347-11e7-9e90-8f98158132bf.png)
![resend invoice](https://user-images.githubusercontent.com/22492841/29399612-8d67ed50-8347-11e7-980d-23fc0c084f37.png)

**Comment by wpdev10** [comment]
PR merged offline while testing the whole plugin. So closing this issue.
