### ISSUE TITLE
Discount count is not working.

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#72]
I have applied discounts to more than one account but it is showing 0 all the time. It should be the count of numbers of times this discount applied.

Screenshots:
![discount count](https://user-images.githubusercontent.com/22492841/29410586-bb3f77e4-836e-11e7-957f-72be406df901.png)
![discount code applied](https://user-images.githubusercontent.com/22492841/29410588-bcb0477a-836e-11e7-8cdb-400adc5f6675.png)

**Comment by kprajapatii** [comment]
Until invoice is not paid, the discount applied to that invoice doesn't included in total no. of uses shown. 
But it is still validated when someone uses that discount for another invoices.

**Comment by wpdev10** [comment]
Ok that is fine!
