### ISSUE TITLE
Suggestion: Disable user email and add new user button if invoice is not pending.

### ISSUE THREAD

**Issue by mdrahul** [AyeCode/invoicing#73]
- We can disable the user email and Add new user button or all user info once the invoice is paid/cancelled/refunded as there is no meaning of changing it.

- We should disable status drop down once the invoice is paid/cancelled/refunded as there is no meaning of changing the status to pending again instead admin should create a new invoice.

- Provide Duplicate Invoice functionality (Metabox/Link) so that admin can recreate the copy of invoices if required.

Screenshots:
![new user disable](https://user-images.githubusercontent.com/22492841/29411465-9257a6d6-8372-11e7-8bfc-f418e6202166.png)

**Comment by Stiofan** [comment]
we should not disable the status change
