### ISSUE TITLE
Typo results in error on WP MultiSite sub blog.

### ISSUE THREAD

**Issue by StonehengeCreations** [AyeCode/invoicing#731]
**Describe the bug**
If you are using the plugin on a WordPress MultiSite sub blog, there is a "minor" typo in `class-getpaid-reports-report-items.php`, line 37.

`INNER JOIN $table2 as item ON item.post_id = wp_posts.ID` results in WordPress fetching the post ID on the main blog.
Correcting this line to `INNER JOIN $table2 as item ON item.post_id = $wpdb->posts.ID` solves the problem.

**Comment by picocodes** [comment]
Thanks @StonehengeCreations, this has been fixed for the next update
