### ISSUE TITLE
Negative total if discount is greater than item price

### ISSUE THREAD

**Issue by gandhirk** [AyeCode/invoicing#75]
1. Create an invoice with an item having price say $10.
2. Apply coupon having a flat discount of $20 and it will be applied successfully.
3. See the total it will be negative as it should be zero(0). It is zero(0) in checkout page but not in invoice edit page and print invoice page.

Screenshots:
![negative total](https://user-images.githubusercontent.com/22492841/29412492-abb16d70-8376-11e7-82a3-7d7554a4e935.png)

**Comment by kprajapatii** [comment]
Fixed
