### ISSUE TITLE
wpinv_get_item_by: bug when field is 'id'

### ISSUE THREAD

**Issue by aayla-secura** [AyeCode/invoicing#751]
[Line 30 of `wpinv-item-functions.php`](https://github.com/AyeCode/invoicing/blob/master/includes/wpinv-item-functions.php#L30) says

```
return wpinv_get_item_by_id( $field );
```

when it should be

```
return wpinv_get_item_by_id( $value );
```

since `$field` is `'id'` and `$value` holds the actual value expected by `wpinv_get_item_by_id`

**Comment by picocodes** [comment]
Hi @aayla-secura,

Thanks for the heads up. We fixed it.
