### ISSUE TITLE
Let user view and pay invoice without being logged in

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#79]
as discussed.

**Comment by Stiofan** [comment]
The pay part works, but we still need to make sure the links sent to users via email can be viewed when logged out.

**Comment by kprajapatii** [comment]
- All invoice link within emails now have invoice_key
- Settings added for "require user to be signed in to view or pay invoice"
If ticked then user needs to be logged in to view or pay, can only view or pay their own invoice
If unticked then  anyone can view or pay the invoice
