### ISSUE TITLE
Can't edit or add invoices that belong to other users

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing#91]
I had this problem on my localhost but at some point it has disapeared.
Now i have installed all updates on one of my live sites and i can't view/add/edit invoices the belong to other users.  
You can check here: https://www.barra-accommodation.co.uk/wp-admin/edit.php?post_type=wpi_invoice
this is a live site, so dont break it, i have changed admin login to the usually test site login.

@kprajapatii @mdrahul discuss with eachother so you are not both working on it, i need this fixed ASAP as i want to release first thing.

**Comment by kprajapatii** [comment]
Fixed
https://github.com/AyeCode/invoicing/pull/93/commits/cb6f46ce8f666b632881e01a024e10063c17fe37
